production:
  auto_close_all_due:
    class: Card::AutoCloseAllDueJob
    schedule: every hour
  auto_reconsider_all_inactive:
    class: Card::AutoReconsiderAllStagnatedJob
    schedule: every hour
  remove_abandoned_creations:
    class: RemoveAbandonedCreationsJob
    schedule: every hour
